### PR TITLE
Update MySql.Data to 8.0.33 to solve https://bugs.mysql.com/bug.php?id=92465

### PR DESCRIPTION
**Pull request by huysentruitw**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Excellent, thanks! It's out as Rebus.MySql 4.0.0-alpha02 on NuGet.org now. Also, I'll probably release it as a proper stable version quite soon 🙂 

Thanks for contributing ❤️

**Comment by huysentruitw** [comment]
Thanks for your quick response @mookid8000 but this is targeting release/2 branch so the version should probably be something like 2.2.0 or so, no?

**Comment by mookid8000** [comment]
Oh, you're right! I've pushed Rebus.MySql 2.2.0 to Nuget.org now 😅

**Comment by huysentruitw** [comment]
Awesome. Thanks!

**Pull request merged**
